done

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,15 +1,26 @@
 #!/usr/bin/env bash
-# Check if all required parameters are provided
-if [ "$#" -lt 3 ]; then
-    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+# Checking for command-line argument
+if [ $# -lt 4 ]
+then
+    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
     exit 1
 fi
 
-# Assign parameters to variables
-FILE_PATH=$2
-SSH_KEY=$1
-USER="ubuntu"
-IP_ADD=3.84.238.226
+# Assigning Arguments to variables
 
-# Transfer the file using scp
-scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" $USER@$IP_ADD:~/
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+
+# Disabbling Strict Host Key checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+# Checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+    echo "FILE TRANSFER WAS SUCCESSFULL"
+else
+    echo "FILE TRANSFER FAILED"
+fi
